name: CI

on:
  push:
    branches:
      - dev
      - staging
      - prod

permissions:
  id-token: write

jobs:
  run-terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    env:
      TF_ENV: ${{ github.ref_name }}

    defaults:
      run:
        working-directory: environments/${{ github.ref_name }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.ROLE_ASSUME }}/terraform.role"
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Run terraform init
        run: terraform init

      - name: Create tfvars file
        run: |
          echo "aws_region = \"${{ secrets.AWS_REGION }}\"" > terraform.tfvars
          echo "service_name = \"${{ secrets.SERVICE_NAME }}\"" >> terraform.tfvars

      # - name: Run terraform format
      #   run: terraform fmt -check -recursive

      - name: Run terraform plan
        run: terraform plan

      - name: Run terraform apply
        run: terraform apply -auto-approve
